services:
  backend:
    build: ./backend
    container_name: api-nest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: ModeladoBDD
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - ./backend/.env

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
